### ISSUE TITLE
순서변경

### ISSUE THREAD

**Issue by OneK-2** [wpdbs1229/wpdbs1229#1]
이 부분 순서를 바꾸는건 어떨까요? 깃허브 스탯이나 언어 통계를 아래로 내리는 방식으로
https://github.com/wpdbs1229/wpdbs1229/blob/0e6d223b71b0696a5035b9e376f2f453b6a43ee1/README.md?plain=1#L31

**Comment by wpdbs1229** [comment]
네네~
